import Foundation

public struct VeteranDecal: Identifiable, Sendable {
    public let id: String
    public let name: String

    // Values from startPers.do's allOptions list, catalog version 2026-09-21.1.
    public static let all: [VeteranDecal] = [
        .init(id: "V00", name: "1st Armored Division Assoc."),
        .init(id: "V01", name: "1st Cavalry Division Assoc."),
        .init(id: "V02", name: "1st Division Society"),
        .init(id: "V03", name: "1st Marine Division Assoc."),
        .init(id: "V04", name: "2nd Infantry Division"),
        .init(id: "V06", name: "3rd Marine Division Assoc."),
        .init(id: "V07", name: "4th Marine Division Assoc."),
        .init(id: "V09", name: "25th Infantry Division Assoc."),
        .init(id: "V10", name: "82nd Airborne Division"),
        .init(id: "V11", name: "101st Airborne Division"),
        .init(id: "V12", name: "173rd Airborne Brigade"),
        .init(id: "V14", name: "Air Force Assoc."),
        .init(id: "V15", name: "Air Force Sergeants Assoc."),
        .init(id: "V16", name: "American GI Forum"),
        .init(id: "V17", name: "American Legion"),
        .init(id: "V20", name: "AMVETS"),
        .init(id: "V24", name: "CA Assoc. of County Veteran Service Officers"),
        .init(id: "V25", name: "CA Department of Veteran Affairs"),
        .init(id: "V30", name: "Combat Infantry Badge"),
        .init(id: "V31", name: "Corps of Engineers"),
        .init(id: "V32", name: "Disabled American Veteran"),
        .init(id: "V38", name: "Jewish War Veterans"),
        .init(id: "V39", name: "Korean War Veterans Assoc."),
        .init(id: "V40", name: "Marine Corps League"),
        .init(id: "V47", name: "National Guard"),
        .init(id: "V50", name: "Paralyzed Veterans Assoc."),
        .init(id: "V51", name: "Persian Gulf Service"),
        .init(id: "V53", name: "Reserve Officers Assoc."),
        .init(id: "V54", name: "Retired Enlisted Assoc."),
        .init(id: "V55", name: "Military Officers Association of America"),
        .init(id: "V57", name: "Seabees"),
        .init(id: "V58", name: "Special Forces Association"),
        .init(id: "V59", name: "US Air Force"),
        .init(id: "V60", name: "US Air Force Academy Assoc. of Graduates"),
        .init(id: "V61", name: "US Army"),
        .init(id: "V62", name: "US Coast Guard"),
        .init(id: "V64", name: "US Marine Corps"),
        .init(id: "V67", name: "US Military Academy Assoc. of Graduates - West Point"),
        .init(id: "V68", name: "US Naval Academy Alumni Assoc."),
        .init(id: "V69", name: "US Navy"),
        .init(id: "V73", name: "Veterans of Foreign Wars"),
        .init(id: "V76", name: "Vietnam Helicopter Pilots Assoc."),
        .init(id: "V77", name: "Vietnam Veterans of America"),
        .init(id: "V87", name: "Association of the US Army"),
        .init(id: "V92", name: "Navy League of the US"),
        .init(id: "V94", name: "US Submarine Veterans Incorporated"),
        .init(id: "V95", name: "Air Force Reserve"),
        .init(id: "W01", name: "4th Infantry Division"),
        .init(id: "W02", name: "Distinguished Flying Cross Society"),
        .init(id: "W03", name: "63rd Infantry Division Association"),
        .init(id: "W04", name: "Lao Veterans of America"),
        .init(id: "W05", name: "11th Airborne Division"),
        .init(id: "W06", name: "POW/MIA"),
        .init(id: "W09", name: "10th Mountain Division"),
        .init(id: "W13", name: "Merchant Marine Division"),
        .init(id: "W23", name: "Afghanistan Campaign Medal"),
        .init(id: "W24", name: "American Campaign Medal"),
        .init(id: "W25", name: "Asiatic-Pacific Campaign Medal"),
        .init(id: "W26", name: "European-African-Middle Eastern Campaign Medal"),
        .init(id: "W27", name: "Global War on Terrorism Expeditionary Medal"),
        .init(id: "W28", name: "Global War on Terrorism Service Medal"),
        .init(id: "W29", name: "Iraq Campaign Medal"),
        .init(id: "W30", name: "Korean Service Medal"),
        .init(id: "W31", name: "Kosovo Campaign Medal"),
        .init(id: "W32", name: "Philippine Defense Medal"),
        .init(id: "W33", name: "Philippine Independence Medal"),
        .init(id: "W34", name: "Philippine Liberation Medal"),
        .init(id: "W35", name: "Republic of Vietnam Campaign Medal"),
        .init(id: "W36", name: "Southwest Asia Service Medal"),
        .init(id: "W37", name: "Vietnam Service Medal"),
        .init(id: "W38", name: "World War II Victory Medal"),
        .init(id: "W39", name: "Support Our Troops Ribbon"),
        .init(id: "W40", name: "Honoring Womens Veterans")
    ]
    public static func decal(id: String) -> VeteranDecal? { all.first { $0.id == id } }
}
